module.exports = {
    authenticateUser: require('./authenticate-user'),
    registerUser: require('./register-user'),
    retrieveUser: require('./retrieve-user'),
    modifyUser: require('./modify-user'),
    deleteUser: require('./delete-user'),
    createLeague: require('./create-league'),
    deleteLeague: require('./delete-league'),
    retrieveLeagues: require('./retrieve-leagues'),
    createTeam: require('./create-team'),
    updateTeam: require('./update-team'),
    deleteTeam: require('./delete-team'),
    retrieveTeam: require('./retrieve-team'),
    retrieveTeamByLeague: require('./retrieve-teambyleague'),
    addTeamToLeague: require('./add-teamtoleague'),
    retrieveLeaguebyTeam: require('./retrieve-leaguebyteam'),
    retrieveLeague: require('./retrieve-league'),
    retrieveTeamByLeague: require('./retrieve-teambyleague'),
    updateLeagueUsers: require('./update-leagueusers'),
    retrieveUserTeams: require('./retrieve-userteams'),
    listTeams: require('./list-teams')
}